### ISSUE TITLE
Requirement | Deploy Site to Render/Heroku

### ISSUE THREAD

**Issue by CLTJared** [coulterkyle/Project-3#9]
Need to setup deployment to Render or Heroku.
- [x] Create Project on Render/Heroku
- [x] Setup link with GitHub to auto-deploy main

**Comment by coulterkyle** [comment]
base site deployed to Render

**Comment by coulterkyle** [comment]
<img width="988" alt="Screenshot 2024-02-29 at 11 06 51 AM" src="https://github.com/coulterkyle/Project-3/assets/152663440/1a380551-16ca-48bd-be2f-04bf48e360ec">
